`timescale 1ns/1ps

module dut_packet_parser (
    input  logic        clk,
    input  logic        rst_n,
    input  logic [15:0] packet_len_i,
    input  logic [7:0]  data_i,
    input  logic        valid_i,
    input  logic        sop_i,
    input  logic        eop_i,
    output logic        ready_o,
    output logic        hdr_valid_o,
    input  logic        hdr_ready_i,
    output logic [159:0] header_bytes_o,
    output logic [3:0]  parse_error_o,
    output logic        checksum_ok_o,
    output logic [3:0]  version_o,
    output logic [3:0]  hdr_len_words_o,
    output logic [7:0]  protocol_o,
    output logic [7:0]  flags_o,
    output logic [7:0]  ttl_o,
    output logic [15:0] total_length_o,
    output logic [15:0] payload_length_o,
    output logic [15:0] src_addr_o,
    output logic [15:0] dst_addr_o,
    output logic [15:0] src_port_o,
    output logic [15:0] dst_port_o,
    output logic [15:0] packet_id_o,
    output logic [7:0]  payload_data_o,
    output logic        payload_valid_o,
    output logic        payload_sop_o,
    output logic        payload_eop_o,
    input  logic        payload_ready_i
);
    packet_header_parser u_parser (
        .clk(clk),
        .rst_n(rst_n),
        .packet_len_i(packet_len_i),
        .data_i(data_i),
        .valid_i(valid_i),
        .sop_i(sop_i),
        .eop_i(eop_i),
        .ready_o(ready_o),
        .hdr_valid_o(hdr_valid_o),
        .hdr_ready_i(hdr_ready_i),
        .header_bytes_o(header_bytes_o),
        .parse_error_o(parse_error_o),
        .checksum_ok_o(checksum_ok_o),
        .version_o(version_o),
        .hdr_len_words_o(hdr_len_words_o),
        .protocol_o(protocol_o),
        .flags_o(flags_o),
        .ttl_o(ttl_o),
        .total_length_o(total_length_o),
        .payload_length_o(payload_length_o),
        .src_addr_o(src_addr_o),
        .dst_addr_o(dst_addr_o),
        .src_port_o(src_port_o),
        .dst_port_o(dst_port_o),
        .packet_id_o(packet_id_o),
        .payload_data_o(payload_data_o),
        .payload_valid_o(payload_valid_o),
        .payload_sop_o(payload_sop_o),
        .payload_eop_o(payload_eop_o),
        .payload_ready_i(payload_ready_i)
    );
endmodule
